version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:UbUdTIq1TgMzaix7e44B7pV9/CREMap5sHoaP4pAdn0"

      - run:
          name: Add EC2 to known hosts
          command: |
            ssh-keyscan -H 16.171.52.75 ~/.ssh/known_hosts

      - run:
          name: Deploy to EC2
          command: |
            ssh ubuntu@16.171.52.75 "
              cd /var/www/html &&
              git pull origin main &&
              sudo systemctl restart nginx
            "

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - deploy

